micronaut:
  server:
    port: 8090
    enabled: false
---
# Management Endpoints in /info and /health etc.
endpoints:
  all:
    port: 8025
    sensitive: false
  info:
    config:
      enabled: true
    refresh:
      enabled: true
---
# Custom data in Endpoint /info
info:
  demo:
    mystring : "webhook-firestore-sink"
---
# Jackson Reflection free JSON processing
jackson:
  bean-introspection-module: true
  module-scan: true
  json-view:
    enabled: true
---
kafka:
  bootstrap:
    servers: pkc-lgk0v.us-west1.gcp.confluent.cloud:9092
  security:
    protocol: SASL_SSL
  sasl:
    mechanism: PLAIN
    jaas:
      config: org.apache.kafka.common.security.plain.PlainLoginModule required username="DF2VARK6NKYQSSGG"
        password="K3jIzZ+vVQpsv6qpfFq9Z6rNbKsjguKtgD/QEk3T1KTitXQjOX1hxn8LrsfhiGgF";
schema:
  registry:
    url: https://psrc-e8157.us-east-2.aws.confluent.cloud
    basic:
      auth:
        user:
          info: ZM7TDZPJI332OB5V:pWT3EbrK4eUPFzB9SkLkksFb7wWNmpK7yFRAhCsg0xKRWZuCZcgB3GszDJ33RPHT
  basic:
    auth:
      credentials:
        source: USER_INFO
  ssl:
    endpoint:
      identification:
        algorithm: https